#ifndef LLP1_CONFIGURATION_H
#define LLP1_CONFIGURATION_H

#define FILE_GRANULARITY 4
#define MINIMAL_TUPLE_SIZE 256
#define SINGLE_TUPLE_VALUE_SIZE 8
#define OFFSET_VALUE_SIZE 8
#define MIN_ID_ARRAY_SIZE 1
#define NULL_VALUE 0
#define INPUT_BUFFER_SIZE 1024
#define BUFFER_COMMAND_SIZE 256
#define BIG_ENDIAN_SIGNATURE 0xFFFE
#define BOOLEAN_TYPE 0
#define INTEGER_TYPE 1
#define FLOAT_TYPE 2
#define STRING_TYPE 3

#endif //LLP1_CONFIGURATION_H
